//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace writeInvoice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCeki
    {
        public int No { get; set; }
        public short AracNo { get; set; }
        public short Palet { get; set; }
        public Nullable<decimal> Net { get; set; }
        public Nullable<decimal> Brut { get; set; }
        public Nullable<decimal> AracNet { get; set; }
        public Nullable<System.DateTime> GirisTarih { get; set; }
        public Nullable<System.DateTime> CikisTarih { get; set; }
    
        public virtual tblDriver tblDriver { get; set; }
    }
}
