//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace writeInvoice
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDocument()
        {
            this.tblScomeName = new HashSet<tblScomeName>();
        }
    
        public short No { get; set; }
        public string Name { get; set; }
        public string FontFamily { get; set; }
        public Nullable<short> FontSize { get; set; }
        public string Head { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblScomeName> tblScomeName { get; set; }
    }
}
